title: Youtube
owner_name: Napoléon Bonaparte Officiel
github_username: will-w-cheng, kinetekenergy, crownedbison, advikg
github_repo: "frontend"
baseurl: "/youtube"

plugins:
- jekyll-remote-theme
future: true
